from enum import Enum


class VoiceType(Enum):
    DORM = "Dorm"
    BATTLE = "Battle"
    COMMUNICATIONS = "Communications"
    SYSTEM = "System"
    OTHER = "Other"


table_languages = ['cn', 'en']


voice_conversion_table: dict[VoiceType, dict[str, tuple[str]]] = {
    VoiceType.DORM: {
        # dorm
        "008": ("早上问候", "Morning greeting"),
        "009": ("晚间问候", "Night greeting"),
        "010": ("深夜问候", "Late night greeting"),

        "005": ("收到邮件", "Mail received"),

        "013": ("元旦", "New Year"),
        "014": ("春节", "Spring Festival"),
        "015": ("圣诞节", "Christmas"),
        "016": ("情人节", "Valentine's Day"),
        "017": ("卡拉彼丘纪念日", "Strinova anniversary"),
        "065": ("七夕", "Qixi Festival"),

        "030": ("战斗胜利", "Winning"),
        "031": ("战斗胜利MVP", "MVP"),
        "032": ("战斗失败", "Losing"),
        "033": ("战斗失败SVP", "SVP"),

        "001": ("点击互动", "Touching"),
        "002": ("点击互动", "Touching"),
        "003": ("点击互动", "Touching"),
        "004": ("摸头", "Head pat"),
        "059": ("互动交谈", "Touching"),
        "060": ("互动交谈", "Touching"),
        "061": ("互动交谈", "Touching"),
        "062": ("互动交谈", "Touching"),
        "063": ("互动交谈", "Touching"),
        "025": ("好感度上升后触碰", "Touching (high favorability)"),
        "026": ("好感度上升后触碰", "Touching (high favorability)"),
        "027": ("好感度上升后触碰", "Touching (high favorability)"),
        "028": ("好感度上升后触碰", "Touching (high favorability)"),
        "029": ("好感度上升后触碰", "Touching (high favorability)"),
        "035": ("好感提升后交谈", "Chatting (friendship 1)"),
        "036": ("好感提升后交谈", "Chatting (friendship 3)"),
        "037": ("好感提升后交谈", "Chatting (friendship 7)"),
        "038": ("好感提升后交谈", "Chatting (friendship 10)"),
        "039": ("打招呼", "Greeting"),
        "040": ("打招呼", "Greeting"),
        "041": ("打招呼", "Greeting"),
        "042": ("打招呼", "Greeting"),
        "043": ("打招呼", "Greeting"),
        "023": ("打招呼", "Greeting (friendship 10)"),
        "044": ("待机", "Idle"),
        "045": ("待机", "Idle"),
        "046": ("待机", "Idle"),
        "047": ("待机", "Idle"),
        "048": ("待机", "Idle"),
        "049": ("打断角色状态", "Interrupting"),
        "050": ("打断角色状态", "Interrupting"),
        "051": ("打断角色状态", "Interrupting"),
        "052": ("打断角色状态", "Interrupting"),
        "053": ("打断角色状态", "Interrupting"),
        "054": ("近景交谈", "Close up chatting"),
        "055": ("近景交谈", "Close up chatting"),
        "058": ("近景交谈", "Close up easter egg"),
        "064": ("好感度10语音", "Friendship 10 easter egg"),
        "024": ("感谢礼物", "Thanking a gift"),
        "056": ("感谢礼物", "Thanking a gift (close up)"),
        "057": ("感谢专属礼物", "Thanking a special gift"),

        "152": ("?", "?"),
        "153": ("?", "?"),
        "154": ("?", "?"),
        "155": ("生气", "Angry"),
        "156": ("安慰玩家", "Comforting the player"),
        "157": ("?", "?"),
        "158": ("?", "?"),
        "159": ("?", "?"),
        "160": ("?", "?"),
        "161": ("?", "?"),
        "162": ("?", "?"),
        "163": ("?", "?"),
        "164": ("?", "?"),
        # no prefix
        "011": ("玩家生日", "Player birthday"),
        "034": ("玩家生日", "Player birthday"),
        "012": ("角色生日", "Character birthday"),
        "700": ("生日贺卡", "Birthday greeting card"),
        "701": ("生日蛋糕", "Birthday cake"),
        "702": ("生日回礼", "Reciprocating birthday gift"),
        "703": ("讨论生日礼物", "Discussing birthday gift"),
        "704": ("收到生日礼物", "Receiving birthday gift"),
        "705": ("收到礼物", "Receiving birthday gift"),
        "006": ("朋友生日", "Friend birthday"),
        "007": ("朋友生日", "Friend birthday"),
    },
    VoiceType.BATTLE: {
        "066": ("选择角色", "Character select"),
        "067": ("确认准备", "Confirm"),
        "068": ("开场台词", "Opening line"),
        "069": ("开场台词", "Opening line"),
        "070": ("开场台词", "Opening line"),
        "071": ("Q技能冷却完毕", "Active skill cooldown complete"),
        "072": ("主动技能", "Active skill"),
        "073": ("主动技能", "Active skill"),
        "074": ("主动技能", "Active skill"),
        "075": ("被动生效", "Passive activated"),
        "076": ("大招充能完毕", "Ultimate charged"),
        "077": ("释放大招", "Ultimate skill"),
        "078": ("释放大招", "Ultimate skill"),
        "079": ("释放大招", "Ultimate skill"),
        "080": ("大招无法使用", "Ultimate unavailable"),
        "108": ("受击", "Getting hit"),
        "109": ("击杀敌人", "Downing an enemy"),
        "110": ("击杀敌人", "Downing an enemy"),
        "111": ("击杀敌人", "Downing an enemy"),
        "112": ("击杀敌人", "Downing an enemy"),
        "113": ("击杀敌人", "Downing an enemy"),
        "114": ("击杀敌人", "Downing an enemy"),
        "115": ("双杀", "Double kill"),
        "116": ("三杀", "Triple kill"),
        "117": ("四杀", "Quadra kill"),
        "118": ("五杀", "Penta kill"),
        "119": ("超神", "God-like"),
        "120": ("复仇", "Revenge"),
        "123": ("被忍锋击倒", "Downed by Ninjato"),
        "124": ("危险区域死亡", "Dying outside the zone"),
        "125": ("摔死", "Falling to death"),
        "126": ("击倒敌人", "Downing an enemy"),
        "127": ("被击倒", "Being downed"),
        "122": ("倒地时间结束后死亡", "Dying after being downed"),
        "121": ("被击杀", "Dying"),
        "128": ("向队友求救", "Seeking a revive"),
        "129": ("救助队友", "Helping a teammate"),
        "130": ("被队友扶起", "Revived by teammate"),
        "131": ("安装炸弹", "Plant bomb"),
        "132": ("捡起炸弹", "Pick up bomb"),
        "133": ("开始拆除炸弹", "Defusing bomb"),
        "134": ("丢弃炸弹", "Abandoning the bomb"),
        "135": ("发现已被安装的炸弹", "Seeing a planted bomb"),
        "136": ("飞行", "Flying"),
        "137": ("失败", "Defeat"),
        "138": ("胜利", "Victory"),
        "139": ("失败SVP", "SVP"),
        "140": ("胜利MVP", "MVP"),
        "141": ("彩蛋", "Easter egg"),
        "142": ("彩蛋", "Easter egg"),
        "143": ("彩蛋", "Easter egg"),
        "144": ("彩蛋", "Easter egg"),
        "145": ("彩蛋", "Easter egg"),
        "146": ("彩蛋", "Easter egg"),
        "147": ("彩蛋", "Easter egg"),
        "148": ("彩蛋", "Easter egg"),
        "149": ("彩蛋", "Easter egg"),
        "150": ("彩蛋", "Easter egg"),
        "500": ("击倒敌人", "Downing an enemy"),
        "501": ("击倒敌人", "Downing an enemy"),
        "502": ("远处有敌人", "Enemy spotted far away"),
        "503": ("远处有敌人", "Enemy spotted far away"),
        "504": ("近处有敌人", "Enemy spotted close by"),
        "505": ("近处有敌人", "Enemy spotted close by"),
        "506": ("多名敌人", "Multiple enemies spotted"),
        "507": ("多名敌人", "Multiple enemies spotted"),
        "508": ("击中敌人", "Enemy hit"),
        "509": ("击中敌人", "Enemy hit"),
        "510": ("击中敌人", "Enemy hit"),
        "511": ("重创敌人", "Enemy heavily hit"),
        "512": ("重创敌人", "Enemy heavily hit"),
        "513": ("敌人重伤", "Enemy low on health"),
        "514": ("受到攻击", "Under attack"),
        "515": ("受到攻击", "Under attack"),
        "516": ("左侧有敌人", "Enemies on the left"),
        "517": ("左侧有敌人", "Enemies on the left"),
        "518": ("右侧有敌人", "Enemies on the right"),
        "519": ("右侧有敌人", "Enemies on the right"),
        "520": ("身后有敌人", "Enemies behind"),
        "521": ("身后有敌人", "Enemies behind"),
    },
    VoiceType.COMMUNICATIONS: {
        "081": ("进攻", "Attack"),
        "082": ("等待", "Wait"),
        "083": ("撤退", "Retreat"),
        "084": ("谢谢", "Thanks"),
        "085": ("称赞", "Praise"),
        "086": ("是", "Yes"),
        "087": ("否", "No"),
        "088": ("抱歉", "My bad"),
        "089": ("你好", "Hi"),
        "090": ("手榴弹", "Grenade"),
        "091": ("拦截者", "Interceptor"),
        "092": ("烟雾弹", "Smoke Bomb"),
        "093": ("闪光弹", "Flashbang"),
        "094": ("治疗雷", "Healing Greande"),
        "095": ("风场雷", "Windstorm Grenade"),
        "096": ("减速雷", "Slow Grenade"),
        "097": ("警报器", "Tattletale"),
        "098": ("危险信号", "Danger"),
        "099": ("我守这里", "Defend"),
        "100": ("需要支援", "Need backup"),
        "101": ("进攻这里", "Attack here"),
        "102": ("注意这里", "Attention here"),
        "103": ("这里可以安装炸弹", "Bomb can be planted here"),
        "104": ("这里有炸弹", "Bomb is here"),
        "105": ("这里有子弹", "Bullets here"),
        "106": ("这里有护甲", "Armor here"),
        "107": ("这里有战术道具", "Grenade here"),
        "151": ("警报器发现敌人", "Tattletale triggered")
    },
    VoiceType.SYSTEM: {
        "001": ("", "Battle starts"),
        "002": ("", "40 seconds left"),
        "003": ("", "20 seconds left"),
        "004": ("", "Battle ends"),
        "005": ("", "Battle lost"),
        "006": ("", "One teammate remaining"),
        "007": ("", "One enemy remaining"),
        "008": ("", "Bomb carrier down"),
        "009": ("", "Bomb dropped in point A"),
        "010": ("", "Bomb dropped in point B"),
        "011": ("", "Bomb planted"),
        "012": ("", "Last game of first half"),
        "013": ("", "Match point"),
        "014": ("", "Switch sides"),
        "015": ("", "Overtime"),
        "016": ("", "10 kills remaining to win"),
        "017": ("", "5 kills remaining to win"),
        "018": ("", "1 kill remaining to win"),
        "019": ("", "10 kills remaining (enemy team)"),
        "020": ("", "5 kills remaining (enemy team)"),
        "021": ("", "1 kill remaining (enemy team)"),
        "022": ("", "First kill"),
        "023": ("", "Tie"),
        "024": ("", "Victory (no death)"),
        "025": ("", "Victory"),
        "026": ("", "Victory"),
        "027": ("", "?"),
        "028": ("", "?"),
        "029": ("", "?"),
        "030": ("", "Select character"),
        "031": ("", "Select character"),
        "032": ("", "Battle start"),
        "033": ("", "Countdown from 5"),
        "034": ("", "Attacking team (bomb carrier)"),
        "035": ("", "Attacking team (not the bomb carrier)"),
        "036": ("", "Defending team"),
        "037": ("", ""),
        "038": ("", ""),
        "039": ("", ""),
        "040": ("", ""),
        "041": ("", ""),
        "042": ("", ""),
        "043": ("", ""),
        "044": ("", ""),
        "045": ("", ""),
        "046": ("", ""),
        "047": ("", ""),
        "048": ("", "Warmup start"),
        "049": ("", "Warmup about to end"),
        "050": ("", "Countdown from 3"),
        "051": ("", "Leading team has scored 20 points"),
        "052": ("", "Leading team has scored 30 points"),
        "053": ("决赛阶段开始", "?"),
        "054": ("决赛阶段开始", "?"),
        "055": ("", "Reverse string zones appearing"),
        "056": ("", ""),
        "057": ("", "Armor activated"),
        "058": ("", "Heavy armor activated"),
        "059": ("", "Light armor activated"),
        "060": ("", ""),
        "061": ("", ""),
        "062": ("", ""),
        "063": ("", ""),
        "064": ("", ""),
        "065": ("", ""),
        "066": ("", ""),
        "067": ("", ""),
        "068": ("", ""),
        "069": ("", ""),
        "070": ("", ""),
        "071": ("", ""),
        "072": ("", ""),
        "073": ("", "Escort attack start"),
        "074": ("", "Escort defense start"),
        "075": ("", "Checkpoint reached"),
        "076": ("", "Payload almost at destination"),
        "077": ("", "Overtime (escort)"),
        "078": ("", "?"),
        "079": ("", "Crystal mine grab start"),
        "080": ("", "Storage depot defense deactivated"),
        "081": ("", "Enemy storage depot defense deactivated"),
        "082": ("", "Enemy Bablo crystal stolen"),
        "083": ("", "Bablo crystal stolen"),
        "084": ("", "Halfway to victory"),
        "085": ("", "Enemies halfway to victory"),
        "086": ("", "Almost winning"),
        "087": ("", "Enemies almost winning"),
        "088": ("", ""),
        "089": ("", ""),
        "090": ("", ""),
        "091": ("", ""),
        "092": ("", ""),
        "093": ("", ""),
        "094": ("", ""),
        "095": ("", ""),
        "096": ("", ""),
        "097": ("", ""),
        "098": ("", ""),
        "099": ("", ""),
        "100": ("", ""),
        "101": ("", ""),
        "102": ("", ""),
        "103": ("", ""),
        "104": ("", ""),
        "105": ("", ""),
        "106": ("", ""),
        "107": ("", ""),
        "108": ("", ""),
        "109": ("", ""),
        "110": ("", ""),
        "111": ("", ""),
        "112": ("", ""),
        "113": ("", ""),
        "114": ("", ""),
        "115": ("", ""),
        "116": ("", "Countdown from 10"),
        "117": ("", "Human resupplies arrived"),
        "118": ("", "Crystalline resupplies arrived"),
        "119": ("", "Final stand"),
        "120": ("", "Final stand"),
        "121": ("", "Crystallines won"),
        "122": ("", "Survived"),
        "123": ("", "Outbreak game end"),
        "124": ("", "?"),
        "125": ("", "?"),
        "126": ("", ""),
        "127": ("", ""),
        "128": ("", ""),
        "129": ("", ""),
        "130": ("", ""),
        "131": ("", ""),
        "132": ("", ""),
        "133": ("", ""),
        "134": ("", ""),
        "135": ("", ""),
        "136": ("", ""),
        "137": ("", ""),
        "138": ("", ""),
        "139": ("", ""),
        "140": ("", ""),
        "141": ("", ""),
        "142": ("", ""),
    },
    VoiceType.OTHER: {
        "022": ("标题", "Title"),
        "018": ("获得角色", "Character obtained"),
        "019": ("查看角色", "Character page"),
        "020": ("装备副武器", "Equip secondary weapon"),
        "021": ("装备战术道具", "Equip grenade"),
    }
}

voice_conversion_table_flat: dict[str, tuple[str]] = dict((k, v) for d in voice_conversion_table.values() for k, v in d.items())
